#!/usr/bin/env bash
#World wide web

get_info() {
    subdomain_info=$(dig "$2" "$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $subdomain_info" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3}'

if [ $# == 1 ]
then
    get_info "$1" "www"
    get_info "$1" "lb-01"
    get_info "$1" "web-01"
    get_info "$1" "web-02"
elif [ $# == 2 ]
then
	get_info "$1" "$2"
fi
