#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

file_path=$1
server_ip=$2
username=$3
private_key_path=$4


if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

scp -o StrictHostKeyChecking=no -i "$private_key_path" "$file_path" "$username@$server_ip:~/"
