#!/bin/bash
#install nginx

sudo apt update
sudo apt install -y nginx

echo "server {
    listen 80 default_server;
    
    server_name ;

     location /hello {
        return 200 "Hello World!";
    }
    location / {
        root /var/www/html;
        index index.html;
    }

}" > /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
