#!/usr/bin/env bash
#install nginx

sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

file="/etc/nginx/sites-available/default"
sudo chmod +w $file
cmd_1="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sudo sed -i "47i $cmd_1" $file

sudo service nginx restart
