#!/usr/bin/env bash
#install nginx

sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/custom_404.html

file="/etc/nginx/sites-available/default"
sudo chmod +w $file
#cmd_1="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
cmd_2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n internal;\n root /var/www/html;\n}"

#sudo sed -i "47i $cmd_1" $file
sudo sed -i "/^server {/a $cmd_2" $file

sudo service nginx restart
