#!/usr/bin/env bash
#Double the number of webservers

sudo apt-get update
sudo apt-get install -y nginx

hostname=$hostname

sudo echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/nginx/nginx.conf

sudo service nginx restart
