#!/usr/bin/env bash
#Double the number of webservers

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i '/server_name _;/ a \\n\tadd_header X-Served-By $host;' /etc/nginx/sites-available/default

sudo service nginx restart
