#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt install haproxy

frontend load_balancer
   bind \*:80
   default_backend allservers

backend allservers
   server 253001-web-01 54.166.128.139:80 check
   server 253001-web-02 54.210.58.153:80 check
