#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo service haproxy start

lb1="wallace lb"
lb2="bind *:80"
lb3="balance roundrobin"
lb4="server 253001-web-01 54.166.128.139 check"
lb5="server 253001-web-02 54.210.58.153 check"

haproxy_default_location="/etc/default/haproxy"
haproxy_config_file="/etc/haproxy/haproxy.cfg"
s="\n\t"; e="\n";

load_balancer_config="${lb1}${s}${lb2}${s}${lb3}${s}${lb4}${s}${lb5}${e}"

sudo service haproxy enable

sudo sed -i "\$a ${load_balancer_config}" "${haproxy_config_file}"

sudo service haproxy restart
