#!/usr/bin/env bash
#Bash script that configures a server to port 80

sudo apt update
sudo apt install -y nginx

echo "listen 80;" | sudo tee -a /etc/nginx/sites-enabled/default > /dev/null

sudo service nginx restart
