#!/usr/bin/env bash
#Bash script that configures a server to port 80

sudo apt update
sudo apt install -y nginx

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
