#!/usr/bin/env bash
#4 bad luck, 8 is your chance

i=0
while [ $i -lt 10 ]; do
    if [ $i -eq 3 ]; then

        echo $"bad luck"
    elif [ $i -eq 7 ]; then

	echo $"good luck"
    else
        echo $"Best School"
    fi
    i=$((i + 1))
done
