#!/bin/bash
#Bash script that displays

hour=0

while [ $hour -le 12 ]; do
    minute=1

    while [ $minute -le 59 ]; do
        echo "Hour: $hour"
        echo "$minute"
        ((minute++))
    done

    ((hour++))
done | head -n 70
